### ISSUE TITLE
Short name of square foot

### ISSUE THREAD

**Issue by mcapocci** [unitsml/unitsdb#33]
https://github.com/unitsml/unitsdb/blob/1b2ee2119e83077fa74052cb391f53b793586f86/units.yaml#L1395

The short name of square foot is 'foot'. The convention for squared quantities seems to be to leave blank, so will raise a PR to do this.

**Comment by ronaldtse** [comment]
@mcapocci thank you for raising this issue. We can confirm that both "square" and "inch" face the same issue of having the `short:` name wrong:

https://github.com/unitsml/unitsdb/blob/1b2ee2119e83077fa74052cb391f53b793586f86/units.yaml#L1395-L1397

https://github.com/unitsml/unitsdb/blob/1b2ee2119e83077fa74052cb391f53b793586f86/units.yaml#L1420-L1422

Curious since this is your first ticket on GitHub and to UnitsML -- how did you find us? 😉 We are very honored!

**Comment by mcapocci** [comment]
Hi! I work for a maritime classification society, and a consortium of classification societies are using UnitsML in the specification of a common file format [OCX](https://3docx.org/).

As always units are a tricky thing, and I've found I cannot decipher and convert without your units DB.

**Comment by ronaldtse** [comment]
This is fantastic news! We would love to support the OCX standard.

In fact, we are considering setting up a page on unitsml.org to list out organizations/projects that use UnitsML. Would OCX be interested in having your logo listed there? We will link back to https://3docx.org/ (or a location of choice, of course)!

**Comment by mcapocci** [comment]
Best to use the contact page [(here)](https://3docx.org/about/contact-us) or email the coordinator directly [ole.christian.astrup@dnv.com](mailto:ole.christian.astrup@dnv.com).

I'm sure he'd be glad to know you're aware of us!

**Comment by ronaldtse** [comment]
Closing as #34 is merged.
